# Site settings
title: Softwer Tester
twitter_username: Balint_Pap
name: Bálint Pap

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://github.com/balint-pap/blog/
 - title: GitHub
   url: https://github.com/balint-pap
 - title: StackOverflow
   url: https://stackoverflow.com/users/4770745/b%c3%a1lint-pap
 #- title: DZone
 # url: https://dzone.com/users/899489/rhinds.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/balintpap/

#Any buzzword skills you want to include
skills:
 - Software Testing
 - Selenium
 - Java
 - Python
 - Ruby
 - Maven
 - Test management tools
 - Groovy
 - Gradle
 - SQL
 - REST
 - CI/CD

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Software Tester
   start: 2019
   end: Ongoing
   employer: 4ig
   description: ...
 - title: Software tester Trainee
   start: 2018
   end: 2019
   employer: Oce
   description: ...

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2020
   subject: Artificial Intelligence and Computer Science
   school: University of Szeged

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/9d68c6a7dea464c96c771c878c499a44
   courses:
    - title: (TODO:)Functional Programming Principles in Scala
      link: #https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: (TODO:)Algorithms Design and Analysis, Part 1
      link: #https://www.coursera.org/specializations/algorithms
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
#   profileurl: https://speakerdeck.com/robhinds
#   talks:
#    - title: Product Management for Engineers
#      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#      conference: API Conference, Berlin 2018
#    - title: Agile Machine Learning - from Theory to Production
#      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - balint-pap/balint-pap.github.io
 - balint-pap/selenium-tests
 - balint-pap/addons-server
 - balint-pap/acceptance-test-harness


#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/4770745/b%c3%a1lint-pap
   flairimageurl: https://stackexchange.com/users/flair/6115605.png

intro: |
  .
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
  .
